version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-role-ui:
    container_name: reporting-hub-bop-role-ui
    image: mojaloop/reporting-hub-bop-role-ui
    build:
      context: .
      cache_from:
        - mojaloop/reporting-hub-bop-role-ui
      args:
        - PUBLIC_PATH=https://localhost:8081/
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3008/
      - REACT_APP_MOCK_API=false
    ports:
      - "8081:8080"
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:8081 -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
