apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-hub-bop-role-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reporting-hub-bop-role-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reporting-hub-bop-role-ui
    spec:
      containers:
      - name: app
        image: ghcr.io/mojaloop/reporting-hub-bop-role-ui:v1.4.1
        ports:
        - containerPort: 8081
        env:
          - name: REACT_APP_API_BASE_URL
            value: /role-assignment
