apiVersion: v1
kind: Service
metadata:
  name: reporting-hub-bop-role-ui
  labels:
    app.kubernetes.io/name: reporting-hub-bop-role-ui
spec:
  ports:
  - port: 80
    targetPort: 8081
    name: http
  selector:
    app.kubernetes.io/name: reporting-hub-bop-role-ui
